AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  SlackUri:
    Type: String
    Description: Slack Uri for sending notification
Resources:
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Timeout: 300
      Environment:
        Variables:
          SLACK_URI: !Ref SlackUri
      Events:
        CloudWatch:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Policies:
        -
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Action:
                - "codepipeline:GetPipeline"
                - "codepipeline:GetPipelineState"
                - "codepipeline:GetPipelineExecution"
                - "codepipeline:ListPipelines"
              Resource: arn:aws:codepipeline:*
